name: Josh Ward
favicon: null
layout_spectrum: 0.2742714767809957
typography_spectrum: 0.690695712575689
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.03814735868945718
  lightness: 0.25222055590711534
  saturation: 0.6901049609296024
  rhythmicContrast: 0.15787715837359428
purpose: []
